from .base_regularizers import BaseWeightRegularizer, BaseEmbeddingRegularizer
from .center_invariant_regularizer import CenterInvariantRegularizer
from .regular_face_regularizer import RegularFaceRegularizer