from .base_loss_wrapper import BaseLossWrapper
from .self_supervised_loss_wrapper import SelfSupervisedLossWrapper
from .cross_batch_memory_wrapper import CrossBatchMemoryWrapper
from .multiple_losses_wrapper import MultipleLossesWrapper